#Applications Configuration
server:
  port: 8091


#to see H2 Console in Browser

spring:
  h2:
    console:
      enabled:true

  #=========================================
  #BD
  #========================================

  datasource:
    url: jdbc:h2:mem:mydb
    driveClassName: org.h2.Driver
    platform: h2
    username: sa
    password:

    #============================================
    #JPA
    #===========================================
  jpa:
      show-sql: true
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
        database-platform: org.hibernate.dialect.H2Dialect
        properties:
          hibernate:
            show_sql: true
            use_sql_comments: false
            format_sql: false
        logging:
          pattern:
            console:"%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"





